get_charging_profiles:
  fields:
    charging_station:
      required: true
      selector:
        text:
    profile_purpose:
      required: true
      selector:
        select:
          translation_key: "profile_purpose_type"
          options:
            - "tx_default_profile"
            - "tx_profile"

set_charging_profile:
  fields:
    charging_station:
      required: true
      selector:
        text:
    charging_profile:
      required: true
      selector:
        object:

clear_charging_profiles:
  fields:
    charging_station:
      example: DE*BMW*EDAKG8468367490WE
      required: true
      selector:
        text:
    profile_purpose:
      required: true
      selector:
        select:
          translation_key: "profile_purpose_type"
          options:
            - "tx_default_profile"
            - "tx_profile"
